---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: backend
  name: backend
spec:
  containers:
  - name: backend
    image: 192.168.2.100:5000/nettool
  restartPolicy: Always
  nodeName: calico-ebpf-worker

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: client
  name: client
spec:
  containers:
  - name: client
    image: 192.168.2.100:5000/nettool
  restartPolicy: Always
  nodeName: calico-ebpf-control-plane

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend
  name: backend-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    run: backend
